### ISSUE TITLE
code drag and drop link adding

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#100]
http://jsfiddle.net/C8yAa/2/

**Comment by sandmanx** [comment]
I am supposing, you want to make this option available to people to directly post links to the bugs by dragging and dropping?

**Comment by seanauriti** [comment]
Yes, this will allow the user to easily enter the issue.

**Comment by sandmanx** [comment]
Where do you want this to be added? Here - http://www.coderbounty.com/post/ or somewhere else?

**Comment by seanauriti** [comment]
Would be great to have it in the header so it works on all pages...

**Comment by lex111** [comment]
I do not really understand, now and so you can drag the link?

**Comment by seanauriti** [comment]
I don’t think we need this anymore. It was supposed to help make it easier
to post but it’s pretty straightforward now and we have plans to auto
populate the issues when someone connects a project. I’ll close this out.
Thanks for taking a look.

**Comment by lex111** [comment]
Ok, what do you recommend doing issues for a beginner?
