### ISSUE TITLE
Make the homepage 3 big images hover and outline like in the design

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#113]
We designed this, when hovering over the POST, CODE, WIN the circle lights up and the button changes color.  I believe it is in the PSD in the gdrive

**Comment by coderbounty-cowboy** [comment]
Coderbounty posted: http://coderbounty.com/issue/56

**Comment by seanauriti** [comment]
Make sure to address this in the new design.

**Comment by lkd70** [comment]
Hmm, How did you intend to do this? Most would attempt it through flash or something, not really a nice approach. Perhaps just doing something simple in CSS would be good? Simple, fast, portable and still interactive...

Bad example as there's obviously some differences in the two images (one is just the background banner you currently have, the other i extracted from the google drive PSD)
https://vgy.me/KRkg2R.gif

Something simple like that, though add a fade transaction duration... Easy to do, only downside is this loads two images, but that's still less than loading entire flash content.


So what were the intentions for this?

**Comment by seanauriti** [comment]
Yes, simple CSS is good, you example looks great.  Thanks for taking a look.

**Comment by seanauriti** [comment]
would also like the button to change color too.  Is it in the design file?  I think we created it there at some point.

**Comment by lkd70** [comment]
I'd not know where to look, if you find anything though, do link me up and I'll try to implement it locally.

**Comment by lkd70** [comment]
If not, I'll go from what I imagine you're aiming for.

**Comment by seanauriti** [comment]
Design files are here - https://drive.google.com/drive/folders/0B27eQuixxEoiNWhIT2ZQeVhJaW8#

**Comment by lkd70** [comment]
Something along these lines, perhaps? 
https://vgy.me/o8PGHC.gif

**Comment by lkd70** [comment]
https://github.com/CoderBounty/coderbounty/pull/214

**Comment by seanauriti** [comment]
For some strange reason, only the middle one is working... Any ideas why this is happening?

**Comment by lkd70** [comment]
I submitted a file edit fix for this a while ago. Please review it.

**Comment by seanauriti** [comment]
Can you send the link? I deployed what you sent...

**Comment by lkd70** [comment]
https://github.com/CoderBounty/coderbounty/pull/215
