### ISSUE TITLE
Sell Page, Add One Time P/U button

### ISSUE THREAD

**Issue by mareiska** [CoderBounty/coderbounty#129]

**Comment by seanauriti** [comment]
Wrong project

**Comment by mareiska** [comment]
Sorry!!!

On Mon, Nov 30, 2015 at 8:51 PM, seanauriti <notifications@github.com>
wrote:

> Closed #129 <https://github.com/CoderBounty/coderbounty/issues/129>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CoderBounty/coderbounty/issues/129#event-478453160>.
>



-- 
Mary Auriti
Alpha One Labs
