### ISSUE TITLE
Add "bounty coverage" 

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#133]
Show percentage of issues with bounties

**Comment by seanauriti** [comment]
related to #106

**Comment by aayushsanghavi** [comment]
What is to be done in this issue? Could you provide some explanation?

**Comment by seanauriti** [comment]
This is a number.  it will say something like 4 out of 50 issues have bounties on them.  It can go on the repository list and grid view.

**Comment by aayushsanghavi** [comment]
Okay, so thats just adding another field in both the views?

**Comment by seanauriti** [comment]
yes

**Comment by aayushsanghavi** [comment]
Great. I'll do this one too. And the field is to be named bounty coverage?

**Comment by seanauriti** [comment]
yes, that sounds good, thank you.

**Comment by aayushsanghavi** [comment]
Thanks merging the code. You might want to close the issue.

**Comment by seanauriti** [comment]
Thank you!
