### ISSUE TITLE
Shorten description to show views on open bounty page

### ISSUE THREAD

**Issue by mareiska** [CoderBounty/coderbounty#143]
Add "more" link (goes to the issue when clicked)  to show the rest of the text in a long description. Also, the word "Views" should be on a separate line than "Posted"

![bountyview](https://cloud.githubusercontent.com/assets/16075543/13273742/c672f988-da73-11e5-964b-7188b8175a11.png)

**Comment by seanauriti** [comment]
Address this in the new design

**Comment by seanauriti** [comment]
This was fixed.
