### ISSUE TITLE
List view for organizations / repositories 

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#150]

**Comment by seanauriti** [comment]
related to #106

**Comment by aayushsanghavi** [comment]
What is to be done? Could you provide some details.

**Comment by seanauriti** [comment]
Similar to the list view for issues, this will show all repositories in an organization or all organizations using coderbounty. Would be goid if it was thinner and more like a table / spreadsheet so more info can be shown.

**Comment by aayushsanghavi** [comment]
Okay, so you want a design for this. How much and what all information about the organisation has to be displayed? And which software did you use to make those designs?

**Comment by seanauriti** [comment]
For org:
Image, #of repositories, total bounty, date updated, 5 contributor images.
All on one thin  line about 30px high.

For repositories:
Image, # of issues, total bounty, programming language, 5 contributor images

Design can be very minimal and can be done directly with existing css
assets.

**Comment by aayushsanghavi** [comment]
I think the design for the list view on #70 would work.

**Comment by seanauriti** [comment]
Yes, can you please make it thinner and better spaced?

**Comment by aayushsanghavi** [comment]
Yeah sure thing. I'll make a new view for it.

**Comment by seanauriti** [comment]
Thank you.

**Comment by aayushsanghavi** [comment]
Thank you for the merge, and just to bring to your attention, issue #106 is technically a part of this issue so you could close that as well.

**Comment by seanauriti** [comment]
Thank you.  #160 is a grid view for the repositories, it is similar.

**Comment by aayushsanghavi** [comment]
Like the grid view for the issues page? Similar content as you mentioned above?

**Comment by seanauriti** [comment]
Yes, with some updates as per the mockup.

**Comment by seanauriti** [comment]
Closed by @aayushsanghavi

**Comment by seanauriti** [comment]
@aayushsanghavi any idea why this list view is off? http://www.coderbounty.com/list/?layout=grid?layout=list

**Comment by aayushsanghavi** [comment]
Hey @seanauriti I'll look into it and let you know. I guess it is something to do with pixels and percentages for the width of the columns.

**Comment by aayushsanghavi** [comment]
@seanauriti I guess the problem is in the list view for issues #70 not the repositories or organization page #255 . I'll look into it though.

**Comment by seanauriti** [comment]
ok, yes, it is the other issue.
