### ISSUE TITLE
Integrate Taken and Solutions on profile pages

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#154]

**Comment by coderbounty-cowboy** [comment]
Coderbounty posted: http://coderbounty.com/issue/52

**Comment by saullocarvalho** [comment]
The github status is not integrated with coderbounty. There this functionality is still open.

**Comment by seanauriti** [comment]
Can you please explain?

**Comment by saullocarvalho** [comment]
The issue is closed on github, while it is open on coderbounty. Which status is the correct one?
