### ISSUE TITLE
Internal Server Error - On Callback from Github Signup

### ISSUE THREAD

**Issue by lteacher** [CoderBounty/coderbounty#177]
Hello,

If you try to sign up with Github, or at least when I try, which I don't think is anything different than others so maybe its just a recent / current problem, you get:
`Internal server error`

Per image:
![image](https://cloud.githubusercontent.com/assets/6103860/16361277/02db15ca-3bce-11e6-9762-49968482cd58.png)

Used Chrome or Firefox, didn't change.

**Comment by seanauriti** [comment]
Thanks for reporting this.  Looking into it now.

**Comment by seanauriti** [comment]
Related to KeyError: 0 #175

**Comment by seanauriti** [comment]
It's fixed!
