### ISSUE TITLE
Make entire div clickable to detail page on the list page

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#192]

**Comment by PixelAtLarge** [comment]
@seanauriti I can take this one. Just to clarify, which of the following are you asking for?

Option #1: Entire issue clickable:

<img width="393" alt="screen shot 2016-10-08 at 1 02 45 pm" src="https://cloud.githubusercontent.com/assets/10035318/19214694/98aebca2-8d57-11e6-8de9-87aca1b8af51.png">

Option #2: Entire issue clickable (with the exception of the `issue-people` section)

<img width="392" alt="screen shot 2016-10-08 at 1 02 53 pm" src="https://cloud.githubusercontent.com/assets/10035318/19214706/c88dfcbc-8d57-11e6-9063-058d623c2298.png">

**Comment by seanauriti** [comment]
Option 2, thank you!

**Comment by PixelAtLarge** [comment]
@seanauriti Unfortunately, having some issues getting this repo to run locally. 

If anybody else wants to grab this issue - please feel free.

**Comment by seanauriti** [comment]
Where did it have issues?  I've sort of resolved the issue by making the text part clickable.
