### ISSUE TITLE
KeyError: 1

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#197]
View details in Rollbar: [https://rollbar.com/coderbounty/Coderbounty/items/44/](https://rollbar.com/coderbounty/Coderbounty/items/44/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/website/views.py", line 564, in get_bounty_image
    'draw.text((size_map[len(str(issue.bounty()))], ...".format(issue.bounty()), (163,75,51),font=font)'
KeyError: 1
```

**Comment by krtkmj** [comment]
Hi @seanauriti, I am working on this.

Can you please explain what `size_map` is in function `website.views.get_bounty_image()` and what should be value for 1 in `size_map` dict?

Thanks

**Comment by seanauriti** [comment]
It can probably be 533 - this is the distance of the text from the edge...  you can see the image that it generates here - http://www.coderbounty.com/get_bounty_image/30/ additionally we need to update the logo to the new logo.
