### ISSUE TITLE
Add pagination to the leaderboard

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#200]

**Comment by sureshdsk** [comment]
I would like to take this.. How many results you want to display per page?

**Comment by seanauriti** [comment]
25 is good

**Comment by sureshdsk** [comment]
@seanauriti  i'm having trouble in setting the project in my mac. I get this error "No module named whitenoise.django" also if you provide a sample db, that would be good.

**Comment by seanauriti** [comment]
Did you run pip install -r requirements.txt?

**Comment by seanauriti** [comment]
Let me know... Feel free to chat with me on slack and I can help you get setup - https://coderbounty-slackin.herokuapp.com/

**Comment by sureshdsk** [comment]
@seanauriti got it working.. Thanks

**Comment by sureshdsk** [comment]
@seanauriti created a PR https://github.com/CoderBounty/coderbounty/pull/220

**Comment by seanauriti** [comment]
Thanks, it's working!
