### ISSUE TITLE
Paid Bounties Page

### ISSUE THREAD

**Issue by mareiska** [CoderBounty/coderbounty#201]
Shouldn't be an option to take it or add more money-- there should be a symbol that indcates that it's been paid
![screen shot 2016-08-14 at 11 25 50 pm](https://cloud.githubusercontent.com/assets/16075543/17655092/e963218e-6277-11e6-810f-6e2019eba22c.png)

**Comment by andela-ijubril** [comment]
Hi @seanauriti, I would like to take a shot at this.

**Comment by seanauriti** [comment]
Awesome, thank you!
