### ISSUE TITLE
Need "Taken" in drop down for Open Bounties

### ISSUE THREAD

**Issue by mareiska** [CoderBounty/coderbounty#205]
So we can see which issues you have been taken and are currently being worked on 
![screen shot 2016-09-09 at 12 11 08 am](https://cloud.githubusercontent.com/assets/16075543/18375242/685f6660-7622-11e6-8b42-77ee411242b0.png)

**Comment by donofriov** [comment]
Hey @seanauriti I'd like to pick this up

**Comment by seanauriti** [comment]
sure!

**Comment by donofriov** [comment]
Sorry, going to have to opt out, didn't realize it was a django/python project. For some reason I just get stuck at "A server error occurred. Please contact the administrator"

**Comment by seanauriti** [comment]
Which page are you seeing that error on?  Feel free to report it using www.bugheist.com

**Comment by donofriov** [comment]
After installing everything via https://github.com/CoderBounty/coderbounty#notes-on-getting-started

And trying to hit the homepage: 127.0.0.1:8000

**Comment by seanauriti** [comment]
Oh, you can see what is going on by setting DEBUG = True in settings.
