### ISSUE TITLE
Create CSS for new list design view

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#207]
Design is done on #70

**Comment by aayushsanghavi** [comment]
Sir, I'd like to take this up. Could you please elaborate on how the design should look?

**Comment by seanauriti** [comment]
The design is on #70

**Comment by seanauriti** [comment]
Thanks again, it is now live.

**Comment by aayushsanghavi** [comment]
Yeah, I saw it on the website. Thank you too for merging my contribution.
