### ISSUE TITLE
bounties list page headers causing overlap

### ISSUE THREAD

**Issue by lkd70** [CoderBounty/coderbounty#213]
Long headers are causing overlap much like the comments were before... Though it's not so great an idea to totally cut the header in two like I did with the comments.

Here's an example showing the issue:
https://vgy.me/kW4p11.png

As you see, due to the length of the h3 block, the starting height of the comment is too low. There's a few ways to combat this... Method I'd do to maintain this slick design is do exactly as I did with the comments, though add a tooltip (jQuery recommended) that contains the full header. Also I think these headers should be treated like titles, in that they act as a link to the bounty "issue" so people don't have to "take" a bounty just to view more details on it. I know the image also does this, but that wasn't clear to me at first.

**Comment by seanauriti** [comment]
Good suggestion, thanks.

**Comment by lkd70** [comment]
Just had a think on a solution to this using just css (to avoid costly JS)
A cross browser solution to this isn't a standard.. What i did get working is something simple though:
https://vgy.me/ZwPg7O.gif

Opinions?

**Comment by seanauriti** [comment]
That looks good, thank you.
