### ISSUE TITLE
Update the logo on the bounty badge

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#225]
http://www.coderbounty.com/get_bounty_image/30/ please update to the new logo

**Comment by JamesFranc** [comment]
On it

**Comment by seanauriti** [comment]
no, that is there for general purpose use.

**Comment by JamesFranc** [comment]
So I was able to get the project to load, after learning about the python stack a little bit, I was able to get the site to load here: [CodeAnywhere ](http://coding-francisjamesii972160.codeanyapp.com:8000/ )  

Pardon my ignorance, but how would I go about recompiling the site so I can see my changes?

**Comment by seanauriti** [comment]
When you save the image, you should be able to see it refresh - http://coding-francisjamesii972160.codeanyapp.com:8000/get_bounty_image/30/  not sure why this link is not working - it works on the live site - http://www.coderbounty.com/get_bounty_image/30/

**Comment by seanauriti** [comment]
This is the base image that needs to change - https://github.com/CoderBounty/coderbounty/blob/master/coderbounty/static/images/layout/github-poster.png  You can get the background from here - https://github.com/CoderBounty/coderbounty/blob/master/coderbounty/static/images/layout/pattern-header.gif
