### ISSUE TITLE
Service matching query does not exist.

### ISSUE THREAD

**Issue by krtkmj** [CoderBounty/coderbounty#228]
Traceback:
    DoesNotExist at /post_all/
    Service matching query does not exist.
    Request Method:	GET
    Request URL:	http://localhost:8000/post_all/
    Django Version:	1.9.5
    Exception Type:	DoesNotExist
    Exception Value:	
    Service matching query does not exist.

**Comment by seanauriti** [comment]
this is a new page, to allow users to post bounties on all issues of the project.
