### ISSUE TITLE
Slow first load = ugly image scroll

### ISSUE THREAD

**Issue by lkd70** [CoderBounty/coderbounty#242]
When first loading the site with no cached items, users with slower connections might experience some loading lagg.

Example: https://vgy.me/1cdzAd.gif

One way to fix this (without reducing image sizes and such) would be to add a preloader.
Just an idea, perhaps someone good with graphics could make a running horse sprite to match the bounty theme... (Keeping in mind it'd need to be small so it could load quickly).

From there it's just a case of making it run in CSS, easily done...

Any thoughts on this idea?

**Comment by seanauriti** [comment]
Good idea! Open to suggestions and fixes... we are planning a redesign soon so a quick fix is welcome.  Could even be a solid color and we realize the post code and win images....
