### ISSUE TITLE
Design a list view for the issues

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#70]

**Comment by seanauriti** [comment]
![list-view](https://cloud.githubusercontent.com/assets/7475382/11457936/8ed64814-9684-11e5-8204-37f36b6a5b26.png)

**Comment by NateBaldwinDesign** [comment]
I'll take this up. Do I need to install the tool to see what all is in need of design? Are you looking for CSS as a deliverable?

**Comment by seanauriti** [comment]
Awesome, that would be great!  No need to install the tool, static assets are in /static

**Comment by NateBaldwinDesign** [comment]
A few additional questions:
1) Are the toggles "Issues" and "Users/Organizations" used as a filter or sort?
2) I'm assuming "recent", "highest bounty", and "most contributors" is a sort filter (pretty common pattern). If that's the case, how does it relate/differentiate from the issues/users toggle? 
3) I see a list/grid view toggle -- this issue only indicates a list view; is that correct?
4) Are there existing designs for this site/tool that should be leveraged?

**Comment by seanauriti** [comment]
1) that toggles the repository / org page - #106
2) Correct, no relation to the first toggle.
3) Yes, that will link to the existing grid view - http://www.coderbounty.com/list/
4) The design files are here - https://goo.gl/xvb6CI

**Comment by NateBaldwinDesign** [comment]
Design file created and uploaded to google drive: https://drive.google.com/open?id=0ByMNnAOIlSqfbFlCa1VRb2Z2am8
![coderbounty_list-view](https://cloud.githubusercontent.com/assets/13972198/18971944/5a06d336-8654-11e6-9d3d-9112f737f76c.jpg)


After looking at the existing DOM structure & proposed design structure, simple CSS rework would not be sufficient so I opted to update the design file instead (can't re-order placement of items in DOM). If you have shell structure for list-view in place (with proposed list-view structure for data) in another issue, I'd be happy to look at it to do some CSS work. Let me know if anything else is needed for this issue

**Comment by seanauriti** [comment]
Awesome!  Thank you so much.  Could you please put in a pull request to close this?  I'll create another issue for the CSS...

**Comment by seanauriti** [comment]
Closed by https://github.com/CoderBounty/coderbounty/pull/208
