### ISSUE TITLE
Extension is inserting too many buttons into the page

### ISSUE THREAD

**Issue by seanauriti** [CoderBounty/coderbounty#80]
![image](https://cloud.githubusercontent.com/assets/7475382/11325956/b2e98cbc-9129-11e5-9782-3b74959fb9bf.png)

**Comment by coderbounty-cowboy** [comment]
Coderbounty posted: http://coderbounty.com/issue/57

**Comment by LayZeeDK** [comment]
Where is the extension installer?

**Comment by seanauriti** [comment]
https://github.com/CoderBounty/coderbounty/tree/master/extension

**Comment by seanauriti** [comment]
Seeing a flash when clicking on other issues.  Can you please also hide it on the issue list page, and only show on the individual issue?

**Comment by seanauriti** [comment]
It is now in the Chrome Web Store! https://chrome.google.com/webstore/detail/coderbounty/ipgemjljbfojhhfpipkoilffgjfhekfp

**Comment by seanauriti** [comment]
This is part of the Extension if you are feeling ambitious :8ball:  https://github.com/CoderBounty/coderbounty/issues/111

**Comment by seanauriti** [comment]
Also this one - https://github.com/CoderBounty/coderbounty/issues/109

**Comment by seanauriti** [comment]
This is mostly working, there is occasionally a flash of a second button, not a major issue.
